[package]
name = "block_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.5.0"
bevy_console = "0.2.3"
nalgebra = "0.29.0"
bevy_flycam = "0.5.1"
